# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e715dc51ebc6a7d7bf816061d88acc9b2764df8e7f8ac7416b1dc5af5c2691eacf35475c3e7eb8ed77d162dc58ea700eb6a96d08c0e651dd18cd0365ff82440f

test:
  secret_key_base: 1821f8e294525ae9193bee4f9c04c320f6afe7e79c22d1d23089c88281b01517123aba314b7ab58f23bb972afd4ffd95ccf970d97e590d3a433069763adfd5d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
